"use client";
import { Avatar } from "@/components/ui/avatar";
import * as React from "react";
import { Book } from "@/types";
import { BookOpen, MessageCircle, Heart, Star, Clock, User, Search, Menu, ChevronLeft,  ChevronDown } from "lucide-react";
import { useParams, usePathname, useRouter } from "next/navigation";
import { useSearchParams } from "next/navigation";

interface BookDetailProps {
  book: Book;
  onSave?: (bookId: string) => void;
  onReview?: (rating: number, content: string) => void;
  className?: string;
}

export const BookDetail = ({
  book,
  onSave,
  onReview,
  className,
}: BookDetailProps) => {
  const router = useRouter();
  const pathname = usePathname();
  const params = useParams();
  const searchParams = useSearchParams();
  const query = searchParams?.get("view") || "reading";

  const [isSaved, setIsSaved] = React.useState(false);
  const [showReviewForm, setShowReviewForm] = React.useState(false);
  const [rating, setRating] = React.useState<number | null>(null);
  const [reviewContent, setReviewContent] = React.useState("");

  const [themeMode, setThemeMode] = React.useState<"light" | "dark">("light");

  return (
    <section className="py-12 md:py-24 bg-background max-w-7xl mx-auto px-4">
      <div className="max-w-7xl mx-auto">
        {/* Back Button and Header */}
        <header className="mb-8 flex items-center gap-3">
          <button
            onClick={() => router.back()}
            className="flex items-center gap-2 text-primary hover:text-primary/90 transition-colors"
            aria-label="Back to library"
          >
            <ChevronLeft className="h-4 w-4" />
            <span>Back to Library</span>
          </button>
          <h1 className="text-3xl font-extrabold">{book.title}</h1>
        </header>

        {/* AI Provenance Badge */}
        <div className="mb-6 flex items-center gap-2 rounded-md px-3 py-1.5 text-sm font-medium">
          <span className="bg-primary/10 text-primary">
            AI Generated
          </span>
          <span className="text-muted-foreground">
            · {book.aiProvenance?.provider || "Unknown"}
          </span>
        </div>

        {/* Book Cover and Info */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
          {/* Cover */}
          <div className="relative">
            <img
              src={book.coverUrl || "/placeholder-cover-large.jpg"}
              alt={book.title}
              className="rounded-lg w-full h-64 object-cover"
            />
            <div className="absolute top-2 left-2 bg-primary text-primary-foreground text-xs rounded">
              Published
            </div>
          </div>

          {/* Info Section */}
          <div>
            <h2 className="text-2xl font-bold mb-1">{book.title}</h2>
            {book.subtitle && (
              <p className="text-muted-foreground mb-4">{book.subtitle}</p>
            )}

            {/* Metadata Row */}
            <div className="grid grid-cols-2 gap-3 mb-6">
              <div>
                <p className="text-sm text-muted-foreground">Creator</p>
                <p className="font-medium">{book.creatorId ? "A. Matthews" : "Unknown"}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">AI Model</p>
                <p className="font-medium">{book.aiProvenance?.model || "Unknown"}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Genre</p>
                <p className="font-medium">{book.genre || "Unknown"}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Reading Time</p>
                <p className="font-medium">{book.readingTime || "Unknown"}</p>
              </div>
            </div>

 {/* AI Transparency Section */}
            <details className="mt-6">
              <summary className="cursor-pointer flex items-center gap-2 rounded-md p-2 bg-secondary/20 hover:bg-secondary/30 transition-colors">
                <span className="text-sm font-medium">AI Transparency</span>
                <ChevronDown className="h-4 w-4 text-muted-foreground" />
              </summary>
              <div className="mt-3 text-sm text-muted-foreground">
                <p className="font-medium">Generated by:</p>
                <p>{book.aiProvenance?.provider || "Unknown"}</p>
                <p className="mt-1">{book.aiProvenance?.model || "Unknown model/version"}</p>
                <p className="mt-2">Human editing:</p>
                <p>{book.aiProvenance?.humanEdited ? "Yes, edited by " + (book.aiProvenance?.humanEditor || "unknown") : "No"}</p>
                <p className="mt-2">Content review:</p>
                <p>{book.status || "Pending"}</p>
              </div>
            </details>
          </div>

          {/* About This Work Section */}
          <div className="space-y-4">
            <h3 className="font-medium text-muted-foreground mb-3">About this work</h3>
            <p className="text-muted-foreground leading-relaxed">
              {book.description || "A captivating work created with the help of AI models, exploring themes of technology and human imagination."}
            </p>

            {/* Table of Contents */}
            <details>
              <summary className="cursor-pointer flex items-center gap-2 rounded-md p-2 bg-secondary/20 hover:bg-secondary/30 transition-colors">
                <span className="text-sm font-medium">Table of contents</span>
                <ChevronDown className="h-4 w-4 text-muted-foreground" />
              </summary>
              <ul className="mt-3 space-y-1 text-sm text-muted-foreground">
                <li>Chapter 1: The Beginning</li>
                <li>Chapter 2: Awakening</li>
                <li>Chapter 3: The Journey</li>
                <li>Chapter 4: The Climax</li>
                <li>Chapter 5: Resolution</li>
              </ul>
           </details>

            {/* Creator Information */}
            <div className="pt-4 border-t border-border">
              <h4 className="font-medium mb-3">About the creator</h4>
              <div className="flex items-center gap-3">
                <Avatar className="h-10 w-10">
                  <User className="h-5 w-5" />
                </Avatar>
                <div>
                  <p className="font-medium">A. Matthews</p>
                  <p className="text-sm text-muted-foreground">Creator since 2023</p>
                </div>
              </div>
              <p className="mt-2 text-sm text-muted-foreground">
                Followers: <span className="font-medium">1.2k</span>
              </p>
            </div>
          </div>

          {/* Reviews and Related Works */}
          <div className="mt-8">
            <h3 className="font-medium text-muted-foreground mb-3">Reviews</h3>
            {/* Reviews would go here */}
          </div>

          {/* Related Works */}
          <div className="mt-8">
            <h3 className="font-medium text-muted-foreground mb-3">Related works</h3>
            {/* Related works would go here */}
          </div>
        </div>

        {/* Reader / Continue Reading Section */}
        <div className="mt-8 pt-8 border-t border-border">
          <h3 className="font-medium text-muted-foreground mb-4">Continue reading</h3>
          <p className="text-muted-foreground">
            Last read at chapter {book.readingProgress?.chapterId || "1"} of {book.readingProgress?.totalChapters || "12"}
          </p>
          <button
            onClick={() => setThemeMode((m) => (m === "dark" ? "light" : "dark"))}
            className="mt-4 rounded-md bg-primary px-4 py-2 text-primary-foreground hover:bg-primary/90 transition-colors"
          >
            Continue reading
          </button>
        </div>
      </div>
    </section>
  );
};